// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.op
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="poke_handler,hls_ip_2017_4_op,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flgb2104-2-i,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.200200,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=243,HLS_SYN_LUT=1275}" *)

module poke_handler (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
ap_continue,
        ap_idle,
        ap_ready,
        poke_V_tag_dout,
        poke_V_tag_empty_n,
        poke_V_tag_read,
        poke_V_data_dout,
        poke_V_data_empty_n,
        poke_V_data_read,
        reqs_incoming_V_sector_off_din,
        reqs_incoming_V_sector_off_full_n,
        reqs_incoming_V_sector_off_write,
        reqs_incoming_V_sector_num_din,
        reqs_incoming_V_sector_num_full_n,
        reqs_incoming_V_sector_num_write,
        reqs_incoming_V_tag_din,
        reqs_incoming_V_tag_full_n,
        reqs_incoming_V_tag_write,
        reqs_incoming_V_rw_din,
        reqs_incoming_V_rw_full_n,
        reqs_incoming_V_rw_write,
        kbuf_addrs_V_din,
        kbuf_addrs_V_full_n,
        kbuf_addrs_V_write,
        dma_read_throttle_params_V_din,
        dma_read_throttle_params_V_full_n,
        dma_read_throttle_params_V_write,
        dma_write_throttle_params_V_din,
        dma_write_throttle_params_V_full_n,
        dma_write_throttle_params_V_write,
        device_read_delay_cycle_cnts_V_din,
        device_read_delay_cycle_cnts_V_full_n,
        device_read_delay_cycle_cnts_V_write,
        device_write_delay_cycle_cnts_V_din,
        device_write_delay_cycle_cnts_V_full_n,
        device_write_delay_cycle_cnts_V_write,
        drive_read_throttle_params_V_din,
        drive_read_throttle_params_V_full_n,
        drive_read_throttle_params_V_write,
        drive_write_throttle_params_V_din,
        drive_write_throttle_params_V_full_n,
        drive_write_throttle_params_V_write,
        app_file_infos_0_V_din,
        app_file_infos_0_V_full_n,
        app_file_infos_0_V_write,
        app_file_infos_1_V_din,
        app_file_infos_1_V_full_n,
        app_file_infos_1_V_write,
        read_mode_app_buf_addrs_V_din,
        read_mode_app_buf_addrs_V_full_n,
        read_mode_app_buf_addrs_V_write,
        write_mode_app_buf_addrs_V_din,
        write_mode_app_buf_addrs_V_full_n,
        write_mode_app_buf_addrs_V_write,
        app_free_buf_V_din,
        app_free_buf_V_full_n,
        app_free_buf_V_write,
        app_write_total_len_V_din,
        app_write_total_len_V_full_n,
        app_write_total_len_V_write,
        app_input_params_V_din,
        app_input_params_V_full_n,
        app_input_params_V_write,
        app_commit_write_buf_V_din,
        app_commit_write_buf_V_full_n,
        app_commit_write_buf_V_write,
        app_is_write_mode_0_V_din,
        app_is_write_mode_0_V_full_n,
        app_is_write_mode_0_V_write,
        app_is_write_mode_1_V_din,
        app_is_write_mode_1_V_full_n,
        app_is_write_mode_1_V_write,
        app_is_write_mode_2_V_din,
        app_is_write_mode_2_V_full_n,
        app_is_write_mode_2_V_write,
        reset_sigs_V_din,
        reset_sigs_V_full_n,
        reset_sigs_V_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output ap_ready; output ap_continue;
input  [31:0] poke_V_tag_dout;
input   poke_V_tag_empty_n;
output   poke_V_tag_read;
input  [31:0] poke_V_data_dout;
input   poke_V_data_empty_n;
output   poke_V_data_read;
output  [31:0] reqs_incoming_V_sector_off_din;
input   reqs_incoming_V_sector_off_full_n;
output   reqs_incoming_V_sector_off_write;
output  [31:0] reqs_incoming_V_sector_num_din;
input   reqs_incoming_V_sector_num_full_n;
output   reqs_incoming_V_sector_num_write;
output  [31:0] reqs_incoming_V_tag_din;
input   reqs_incoming_V_tag_full_n;
output   reqs_incoming_V_tag_write;
output   reqs_incoming_V_rw_din;
input   reqs_incoming_V_rw_full_n;
output   reqs_incoming_V_rw_write;
output  [31:0] kbuf_addrs_V_din;
input   kbuf_addrs_V_full_n;
output   kbuf_addrs_V_write;
output  [31:0] dma_read_throttle_params_V_din;
input   dma_read_throttle_params_V_full_n;
output   dma_read_throttle_params_V_write;
output  [31:0] dma_write_throttle_params_V_din;
input   dma_write_throttle_params_V_full_n;
output   dma_write_throttle_params_V_write;
output  [31:0] device_read_delay_cycle_cnts_V_din;
input   device_read_delay_cycle_cnts_V_full_n;
output   device_read_delay_cycle_cnts_V_write;
output  [31:0] device_write_delay_cycle_cnts_V_din;
input   device_write_delay_cycle_cnts_V_full_n;
output   device_write_delay_cycle_cnts_V_write;
output  [31:0] drive_read_throttle_params_V_din;
input   drive_read_throttle_params_V_full_n;
output   drive_read_throttle_params_V_write;
output  [31:0] drive_write_throttle_params_V_din;
input   drive_write_throttle_params_V_full_n;
output   drive_write_throttle_params_V_write;
output  [31:0] app_file_infos_0_V_din;
input   app_file_infos_0_V_full_n;
output   app_file_infos_0_V_write;
output  [31:0] app_file_infos_1_V_din;
input   app_file_infos_1_V_full_n;
output   app_file_infos_1_V_write;
output  [31:0] read_mode_app_buf_addrs_V_din;
input   read_mode_app_buf_addrs_V_full_n;
output   read_mode_app_buf_addrs_V_write;
output  [31:0] write_mode_app_buf_addrs_V_din;
input   write_mode_app_buf_addrs_V_full_n;
output   write_mode_app_buf_addrs_V_write;
output   app_free_buf_V_din;
input   app_free_buf_V_full_n;
output   app_free_buf_V_write;
output  [63:0] app_write_total_len_V_din;
input   app_write_total_len_V_full_n;
output   app_write_total_len_V_write;
output  [31:0] app_input_params_V_din;
input   app_input_params_V_full_n;
output   app_input_params_V_write;
output  [31:0] app_commit_write_buf_V_din;
input   app_commit_write_buf_V_full_n;
output   app_commit_write_buf_V_write;
output   app_is_write_mode_0_V_din;
input   app_is_write_mode_0_V_full_n;
output   app_is_write_mode_0_V_write;
output   app_is_write_mode_1_V_din;
input   app_is_write_mode_1_V_full_n;
output   app_is_write_mode_1_V_write;
output   app_is_write_mode_2_V_din;
input   app_is_write_mode_2_V_full_n;
output   app_is_write_mode_2_V_write;
output   reset_sigs_V_din;
input   reset_sigs_V_full_n;
output   reset_sigs_V_write;

reg ap_idle;
reg[31:0] reqs_incoming_V_sector_off_din;
reg[31:0] reqs_incoming_V_sector_num_din;
reg[31:0] reqs_incoming_V_tag_din;
reg reqs_incoming_V_rw_din;
reg kbuf_addrs_V_write;
reg dma_read_throttle_params_V_write;
reg dma_write_throttle_params_V_write;
reg device_read_delay_cycle_cnts_V_write;
reg device_write_delay_cycle_cnts_V_write;
reg drive_read_throttle_params_V_write;
reg drive_write_throttle_params_V_write;
reg app_file_infos_0_V_write;
reg app_file_infos_1_V_write;
reg read_mode_app_buf_addrs_V_write;
reg write_mode_app_buf_addrs_V_write;
reg app_free_buf_V_write;
reg app_write_total_len_V_write;
reg app_input_params_V_write;
reg app_commit_write_buf_V_write;
reg app_is_write_mode_0_V_write;
reg app_is_write_mode_1_V_write;
reg app_is_write_mode_2_V_write;
reg reset_sigs_V_write;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    reqs_incoming_V_sector_off_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] tmp_14_reg_1244;
reg   [0:0] tmp_15_reg_1248;
reg   [0:0] tmp_17_reg_1252;
reg    reqs_incoming_V_sector_num_blk_n;
reg    reqs_incoming_V_tag_blk_n;
reg    reqs_incoming_V_rw_blk_n;
reg    kbuf_addrs_V_blk_n;
reg   [0:0] tmp_18_reg_1256;
reg    dma_read_throttle_params_V_blk_n;
reg   [0:0] tmp_20_reg_1260;
reg   [0:0] is_read_host_throttle_params_load_reg_1312;
reg    dma_write_throttle_params_V_blk_n;
reg    device_read_delay_cycle_cnts_V_blk_n;
reg   [0:0] tmp_21_reg_1264;
reg    device_write_delay_cycle_cnts_V_blk_n;
reg    drive_read_throttle_params_V_blk_n;
reg   [0:0] tmp_22_reg_1268;
reg   [0:0] is_read_device_throttle_params_load_reg_1308;
reg    drive_write_throttle_params_V_blk_n;
reg    read_mode_app_buf_addrs_V_blk_n;
reg   [0:0] tmp_23_reg_1272;
reg   [0:0] tmp_27_reg_1276;
reg    write_mode_app_buf_addrs_V_blk_n;
reg    app_free_buf_V_blk_n;
reg   [0:0] tmp_28_reg_1280;
reg    app_write_total_len_V_blk_n;
reg   [0:0] tmp_29_reg_1284;
reg   [0:0] tmp_30_reg_1288;
reg   [0:0] tmp_31_reg_1292;
reg   [0:0] tmp_32_reg_1296;
reg   [0:0] has_half_write_total_len_load_reg_1304;
reg    app_input_params_V_blk_n;
reg    app_commit_write_buf_V_blk_n;
reg    app_is_write_mode_0_V_blk_n;
reg   [0:0] tmp_33_reg_1300;
reg    app_is_write_mode_1_V_blk_n;
reg    app_is_write_mode_2_V_blk_n;
reg    reset_sigs_V_blk_n;
wire   [0:0] empty_n_1_fu_760_p1;
reg   [0:0] empty_n_1_reg_1155;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
reg    ap_predicate_op167_write_state4;
reg    ap_predicate_op178_write_state4;
reg    ap_predicate_op180_write_state4;
reg    ap_predicate_op181_write_state4;
reg    ap_predicate_op182_write_state4;
reg    ap_predicate_op183_write_state4;
reg    ap_predicate_op184_write_state4;
reg    ap_predicate_op186_write_state4;
reg    ap_predicate_op187_write_state4;
reg    ap_predicate_op188_write_state4;
reg    ap_predicate_op190_write_state4;
reg    ap_predicate_op191_write_state4;
reg    ap_predicate_op192_write_state4;
wire    reqs_incoming_V_rw1_status;
reg    ap_predicate_op202_write_state4;
reg    ap_predicate_op212_write_state4;
reg    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] tmp_tag_4_reg_1159;
reg   [31:0] ap_reg_pp0_iter1_tmp_tag_4_reg_1159;
reg   [31:0] tmp_data_reg_1165;
reg   [31:0] ap_reg_pp0_iter1_tmp_data_reg_1165;
wire   [2:0] tmp_2_fu_772_p1;
reg   [2:0] tmp_2_reg_1186;
reg   [2:0] ap_reg_pp0_iter1_tmp_2_reg_1186;
wire   [0:0] icmp_fu_786_p2;
reg   [0:0] icmp_reg_1192;
wire   [0:0] icmp3_fu_802_p2;
reg   [0:0] icmp3_reg_1196;
wire   [0:0] tmp_3_fu_808_p2;
reg   [0:0] tmp_3_reg_1200;
wire   [0:0] tmp_4_fu_814_p2;
reg   [0:0] tmp_4_reg_1204;
wire   [0:0] tmp_5_fu_820_p2;
reg   [0:0] tmp_5_reg_1208;
wire   [0:0] tmp_6_fu_826_p2;
reg   [0:0] tmp_6_reg_1212;
wire   [0:0] tmp_7_fu_832_p2;
reg   [0:0] tmp_7_reg_1216;
wire   [0:0] tmp_8_fu_838_p2;
reg   [0:0] tmp_8_reg_1220;
wire   [0:0] tmp_9_fu_844_p2;
reg   [0:0] tmp_9_reg_1224;
wire   [0:0] tmp_s_fu_850_p2;
reg   [0:0] tmp_s_reg_1228;
wire   [0:0] tmp_10_fu_856_p2;
reg   [0:0] tmp_10_reg_1232;
wire   [0:0] tmp_11_fu_862_p2;
reg   [0:0] tmp_11_reg_1236;
wire   [0:0] tmp_12_fu_868_p2;
reg   [0:0] tmp_12_reg_1240;
wire   [0:0] tmp_14_fu_888_p2;
wire   [0:0] tmp_15_fu_894_p2;
wire   [0:0] tmp_17_fu_900_p2;
wire   [0:0] tmp_18_fu_906_p2;
wire   [0:0] tmp_20_fu_912_p2;
wire   [0:0] tmp_21_fu_918_p2;
wire   [0:0] tmp_22_fu_924_p2;
wire   [0:0] tmp_23_fu_930_p2;
wire   [0:0] tmp_27_fu_936_p2;
wire   [0:0] tmp_28_fu_942_p2;
wire   [0:0] tmp_29_fu_948_p2;
wire   [0:0] tmp_30_fu_954_p2;
wire   [0:0] tmp_31_fu_960_p2;
wire   [0:0] tmp_32_fu_966_p2;
wire   [0:0] tmp_33_fu_972_p2;
wire   [0:0] has_half_write_total_len_load_load_fu_978_p1;
wire   [0:0] is_read_device_throttle_params_load_load_fu_986_p1;
wire   [0:0] is_read_host_throttle_params_load_load_fu_994_p1;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg   [4:0] ap_phi_mux_state_s_phi_fu_676_p30;
wire   [4:0] p_s_fu_879_p3;
reg   [4:0] ap_phi_reg_pp0_iter1_state_s_reg_659;
wire   [4:0] ap_phi_reg_pp0_iter0_state_s_reg_659;
reg    poke_V_tag0_update;
wire   [0:0] empty_n_nbread_fu_498_p3_0;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] tmp_38_fu_1002_p2;
wire   [63:0] write_total_len_2_fu_1044_p3;
reg    reqs_incoming_V_rw1_update;
wire   [31:0] req_sector_off_5_fu_1058_p1;
wire   [31:0] req_sector_off_4_fu_1092_p1;
wire   [31:0] tmp_sector_num_3_fu_1072_p1;
wire   [31:0] tmp_sector_num_1_fu_1106_p1;
wire  signed [31:0] tmp_tag_3_fu_1087_p1;
wire  signed [31:0] tmp_tag_1_fu_1121_p1;
reg   [0:0] has_half_write_total_len_fu_482;
reg   [0:0] is_read_device_throttle_params_fu_486;
reg   [0:0] is_read_host_throttle_params_fu_490;
reg   [63:0] tmp_fu_494;
wire   [63:0] write_total_len_fu_1010_p3;
wire   [22:0] tmp_16_fu_776_p4;
wire   [23:0] tmp_24_fu_792_p4;
wire   [0:0] tmp_13_fu_874_p2;
wire   [31:0] tmp_34_fu_1025_p1;
wire   [31:0] tmp_36_fu_1034_p4;
wire   [31:0] tmp_35_fu_1029_p2;
wire   [28:0] grp_fu_737_p4;
wire   [3:0] tmp_19_cast_fu_1063_p1;
wire   [3:0] req_sector_num_1_fu_1066_p2;
wire   [29:0] grp_fu_746_p4;
wire   [30:0] tmp_20_cast_fu_1077_p1;
wire   [30:0] req_tag_1_fu_1081_p2;
wire   [3:0] tmp_16_cast_fu_1097_p1;
wire   [3:0] req_sector_num_fu_1100_p2;
wire   [30:0] tmp_17_cast_fu_1111_p1;
wire   [30:0] req_tag_fu_1115_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_581;
reg    ap_condition_587;
reg    ap_condition_594;
reg    ap_condition_602;
reg    ap_condition_611;
reg    ap_condition_621;
reg    ap_condition_632;
reg    ap_condition_644;
reg    ap_condition_657;
reg    ap_condition_671;
reg    ap_condition_686;
reg    ap_condition_702;
reg    ap_condition_571;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_571)) begin
        if ((1'b1 == ap_condition_702)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_659 <= 5'd15;
        end else if ((1'b1 == ap_condition_686)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_659 <= 5'd14;
        end else if ((1'b1 == ap_condition_671)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_659 <= 5'd13;
        end else if ((1'b1 == ap_condition_657)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_659 <= 5'd12;
        end else if ((1'b1 == ap_condition_644)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_659 <= 5'd11;
        end else if ((1'b1 == ap_condition_632)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_659 <= 5'd10;
        end else if ((1'b1 == ap_condition_621)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_659 <= 5'd9;
        end else if ((1'b1 == ap_condition_611)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_659 <= 5'd7;
        end else if ((1'b1 == ap_condition_602)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_659 <= 5'd6;
        end else if ((1'b1 == ap_condition_594)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_659 <= 5'd5;
        end else if ((1'b1 == ap_condition_587)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_659 <= 5'd3;
        end else if ((1'b1 == ap_condition_581)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_659 <= 5'd2;
        end else if (((empty_n_1_fu_760_p1 == 1'd1) & (icmp_fu_786_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_state_s_reg_659 <= 5'd1;
        end else if ((empty_n_1_fu_760_p1 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_659 <= 5'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_659 <= ap_phi_reg_pp0_iter0_state_s_reg_659;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_32_fu_966_p2 == 1'd1) & (has_half_write_total_len_load_load_fu_978_p1 == 1'd0) & (tmp_31_fu_960_p2 == 1'd0) & (tmp_30_fu_954_p2 == 1'd0) & (tmp_29_fu_948_p2 == 1'd0) & (tmp_28_fu_942_p2 == 1'd0) & (tmp_27_fu_936_p2 == 1'd0) & (tmp_23_fu_930_p2 == 1'd0) & (tmp_22_fu_924_p2 == 1'd0) & (tmp_21_fu_918_p2 == 1'd0) & (tmp_20_fu_912_p2 == 1'd0) & (tmp_18_fu_906_p2 == 1'd0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0))) begin
        has_half_write_total_len_fu_482 <= 1'd1;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (has_half_write_total_len_load_load_fu_978_p1 == 1'd1) & (tmp_32_fu_966_p2 == 1'd1) & (tmp_31_fu_960_p2 == 1'd0) & (tmp_30_fu_954_p2 == 1'd0) & (tmp_29_fu_948_p2 == 1'd0) & (tmp_28_fu_942_p2 == 1'd0) & (tmp_27_fu_936_p2 == 1'd0) & (tmp_23_fu_930_p2 == 1'd0) & (tmp_22_fu_924_p2 == 1'd0) & (tmp_21_fu_918_p2 == 1'd0) & (tmp_20_fu_912_p2 == 1'd0) & (tmp_18_fu_906_p2 == 1'd0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        has_half_write_total_len_fu_482 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (is_read_device_throttle_params_load_load_fu_986_p1 == 1'd1) & (tmp_22_fu_924_p2 == 1'd1) & (tmp_21_fu_918_p2 == 1'd0) & (tmp_20_fu_912_p2 == 1'd0) & (tmp_18_fu_906_p2 == 1'd0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0))) begin
        is_read_device_throttle_params_fu_486 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_22_fu_924_p2 == 1'd1) & (is_read_device_throttle_params_load_load_fu_986_p1 == 1'd0) & (tmp_21_fu_918_p2 == 1'd0) & (tmp_20_fu_912_p2 == 1'd0) & (tmp_18_fu_906_p2 == 1'd0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        is_read_device_throttle_params_fu_486 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (is_read_host_throttle_params_load_load_fu_994_p1 == 1'd1) & (tmp_20_fu_912_p2 == 1'd1) & (tmp_18_fu_906_p2 == 1'd0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0))) begin
        is_read_host_throttle_params_fu_490 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_20_fu_912_p2 == 1'd1) & (is_read_host_throttle_params_load_load_fu_994_p1 == 1'd0) & (tmp_18_fu_906_p2 == 1'd0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        is_read_host_throttle_params_fu_490 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op178_write_state4 == 1'b1))) begin
        tmp_fu_494 <= write_total_len_2_fu_1044_p3;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_32_reg_1296 == 1'd1) & (has_half_write_total_len_load_reg_1304 == 1'd0) & (tmp_31_reg_1292 == 1'd0) & (tmp_30_reg_1288 == 1'd0) & (tmp_29_reg_1284 == 1'd0) & (tmp_28_reg_1280 == 1'd0) & (tmp_27_reg_1276 == 1'd0) & (tmp_23_reg_1272 == 1'd0) & (tmp_22_reg_1268 == 1'd0) & (tmp_21_reg_1264 == 1'd0) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0))) begin
        tmp_fu_494 <= write_total_len_fu_1010_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_fu_494 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_reg_pp0_iter1_tmp_2_reg_1186 <= tmp_2_reg_1186;
        ap_reg_pp0_iter1_tmp_data_reg_1165 <= tmp_data_reg_1165;
        ap_reg_pp0_iter1_tmp_tag_4_reg_1159 <= tmp_tag_4_reg_1159;
        empty_n_1_reg_1155 <= empty_n_nbread_fu_498_p3_0;
        tmp_14_reg_1244 <= tmp_14_fu_888_p2;
        tmp_2_reg_1186 <= tmp_2_fu_772_p1;
        tmp_data_reg_1165 <= poke_V_data_dout;
        tmp_tag_4_reg_1159 <= poke_V_tag_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_32_fu_966_p2 == 1'd1) & (tmp_31_fu_960_p2 == 1'd0) & (tmp_30_fu_954_p2 == 1'd0) & (tmp_29_fu_948_p2 == 1'd0) & (tmp_28_fu_942_p2 == 1'd0) & (tmp_27_fu_936_p2 == 1'd0) & (tmp_23_fu_930_p2 == 1'd0) & (tmp_22_fu_924_p2 == 1'd0) & (tmp_21_fu_918_p2 == 1'd0) & (tmp_20_fu_912_p2 == 1'd0) & (tmp_18_fu_906_p2 == 1'd0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0))) begin
        has_half_write_total_len_load_reg_1304 <= has_half_write_total_len_fu_482;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1))) begin
        icmp3_reg_1196 <= icmp3_fu_802_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (empty_n_1_fu_760_p1 == 1'd1))) begin
        icmp_reg_1192 <= icmp_fu_786_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_22_fu_924_p2 == 1'd1) & (tmp_21_fu_918_p2 == 1'd0) & (tmp_20_fu_912_p2 == 1'd0) & (tmp_18_fu_906_p2 == 1'd0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0))) begin
        is_read_device_throttle_params_load_reg_1308 <= is_read_device_throttle_params_fu_486;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_20_fu_912_p2 == 1'd1) & (tmp_18_fu_906_p2 == 1'd0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0))) begin
        is_read_host_throttle_params_load_reg_1312 <= is_read_host_throttle_params_fu_490;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_802_p2 == 1'd1) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1) & (tmp_s_fu_850_p2 == 1'd0) & (tmp_9_fu_844_p2 == 1'd0) & (tmp_8_fu_838_p2 == 1'd0) & (tmp_7_fu_832_p2 == 1'd0) & (tmp_6_fu_826_p2 == 1'd0) & (tmp_5_fu_820_p2 == 1'd0) & (tmp_4_fu_814_p2 == 1'd0) & (tmp_3_fu_808_p2 == 1'd0))) begin
        tmp_10_reg_1232 <= tmp_10_fu_856_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_802_p2 == 1'd1) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1) & (tmp_10_fu_856_p2 == 1'd0) & (tmp_s_fu_850_p2 == 1'd0) & (tmp_9_fu_844_p2 == 1'd0) & (tmp_8_fu_838_p2 == 1'd0) & (tmp_7_fu_832_p2 == 1'd0) & (tmp_6_fu_826_p2 == 1'd0) & (tmp_5_fu_820_p2 == 1'd0) & (tmp_4_fu_814_p2 == 1'd0) & (tmp_3_fu_808_p2 == 1'd0))) begin
        tmp_11_reg_1236 <= tmp_11_fu_862_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_802_p2 == 1'd1) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1) & (tmp_11_fu_862_p2 == 1'd0) & (tmp_10_fu_856_p2 == 1'd0) & (tmp_s_fu_850_p2 == 1'd0) & (tmp_9_fu_844_p2 == 1'd0) & (tmp_8_fu_838_p2 == 1'd0) & (tmp_7_fu_832_p2 == 1'd0) & (tmp_6_fu_826_p2 == 1'd0) & (tmp_5_fu_820_p2 == 1'd0) & (tmp_4_fu_814_p2 == 1'd0) & (tmp_3_fu_808_p2 == 1'd0))) begin
        tmp_12_reg_1240 <= tmp_12_fu_868_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_14_fu_888_p2 == 1'd0))) begin
        tmp_15_reg_1248 <= tmp_15_fu_894_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0))) begin
        tmp_17_reg_1252 <= tmp_17_fu_900_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0))) begin
        tmp_18_reg_1256 <= tmp_18_fu_906_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_18_fu_906_p2 == 1'd0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0))) begin
        tmp_20_reg_1260 <= tmp_20_fu_912_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_20_fu_912_p2 == 1'd0) & (tmp_18_fu_906_p2 == 1'd0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0))) begin
        tmp_21_reg_1264 <= tmp_21_fu_918_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_21_fu_918_p2 == 1'd0) & (tmp_20_fu_912_p2 == 1'd0) & (tmp_18_fu_906_p2 == 1'd0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0))) begin
        tmp_22_reg_1268 <= tmp_22_fu_924_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_22_fu_924_p2 == 1'd0) & (tmp_21_fu_918_p2 == 1'd0) & (tmp_20_fu_912_p2 == 1'd0) & (tmp_18_fu_906_p2 == 1'd0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0))) begin
        tmp_23_reg_1272 <= tmp_23_fu_930_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_23_fu_930_p2 == 1'd0) & (tmp_22_fu_924_p2 == 1'd0) & (tmp_21_fu_918_p2 == 1'd0) & (tmp_20_fu_912_p2 == 1'd0) & (tmp_18_fu_906_p2 == 1'd0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0))) begin
        tmp_27_reg_1276 <= tmp_27_fu_936_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_27_fu_936_p2 == 1'd0) & (tmp_23_fu_930_p2 == 1'd0) & (tmp_22_fu_924_p2 == 1'd0) & (tmp_21_fu_918_p2 == 1'd0) & (tmp_20_fu_912_p2 == 1'd0) & (tmp_18_fu_906_p2 == 1'd0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0))) begin
        tmp_28_reg_1280 <= tmp_28_fu_942_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_28_fu_942_p2 == 1'd0) & (tmp_27_fu_936_p2 == 1'd0) & (tmp_23_fu_930_p2 == 1'd0) & (tmp_22_fu_924_p2 == 1'd0) & (tmp_21_fu_918_p2 == 1'd0) & (tmp_20_fu_912_p2 == 1'd0) & (tmp_18_fu_906_p2 == 1'd0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0))) begin
        tmp_29_reg_1284 <= tmp_29_fu_948_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_29_fu_948_p2 == 1'd0) & (tmp_28_fu_942_p2 == 1'd0) & (tmp_27_fu_936_p2 == 1'd0) & (tmp_23_fu_930_p2 == 1'd0) & (tmp_22_fu_924_p2 == 1'd0) & (tmp_21_fu_918_p2 == 1'd0) & (tmp_20_fu_912_p2 == 1'd0) & (tmp_18_fu_906_p2 == 1'd0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0))) begin
        tmp_30_reg_1288 <= tmp_30_fu_954_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_30_fu_954_p2 == 1'd0) & (tmp_29_fu_948_p2 == 1'd0) & (tmp_28_fu_942_p2 == 1'd0) & (tmp_27_fu_936_p2 == 1'd0) & (tmp_23_fu_930_p2 == 1'd0) & (tmp_22_fu_924_p2 == 1'd0) & (tmp_21_fu_918_p2 == 1'd0) & (tmp_20_fu_912_p2 == 1'd0) & (tmp_18_fu_906_p2 == 1'd0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0))) begin
        tmp_31_reg_1292 <= tmp_31_fu_960_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_31_fu_960_p2 == 1'd0) & (tmp_30_fu_954_p2 == 1'd0) & (tmp_29_fu_948_p2 == 1'd0) & (tmp_28_fu_942_p2 == 1'd0) & (tmp_27_fu_936_p2 == 1'd0) & (tmp_23_fu_930_p2 == 1'd0) & (tmp_22_fu_924_p2 == 1'd0) & (tmp_21_fu_918_p2 == 1'd0) & (tmp_20_fu_912_p2 == 1'd0) & (tmp_18_fu_906_p2 == 1'd0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0))) begin
        tmp_32_reg_1296 <= tmp_32_fu_966_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_32_fu_966_p2 == 1'd0) & (tmp_31_fu_960_p2 == 1'd0) & (tmp_30_fu_954_p2 == 1'd0) & (tmp_29_fu_948_p2 == 1'd0) & (tmp_28_fu_942_p2 == 1'd0) & (tmp_27_fu_936_p2 == 1'd0) & (tmp_23_fu_930_p2 == 1'd0) & (tmp_22_fu_924_p2 == 1'd0) & (tmp_21_fu_918_p2 == 1'd0) & (tmp_20_fu_912_p2 == 1'd0) & (tmp_18_fu_906_p2 == 1'd0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0))) begin
        tmp_33_reg_1300 <= tmp_33_fu_972_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_802_p2 == 1'd1) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1))) begin
        tmp_3_reg_1200 <= tmp_3_fu_808_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_802_p2 == 1'd1) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1) & (tmp_3_fu_808_p2 == 1'd0))) begin
        tmp_4_reg_1204 <= tmp_4_fu_814_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_802_p2 == 1'd1) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1) & (tmp_4_fu_814_p2 == 1'd0) & (tmp_3_fu_808_p2 == 1'd0))) begin
        tmp_5_reg_1208 <= tmp_5_fu_820_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_802_p2 == 1'd1) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1) & (tmp_5_fu_820_p2 == 1'd0) & (tmp_4_fu_814_p2 == 1'd0) & (tmp_3_fu_808_p2 == 1'd0))) begin
        tmp_6_reg_1212 <= tmp_6_fu_826_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_802_p2 == 1'd1) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1) & (tmp_6_fu_826_p2 == 1'd0) & (tmp_5_fu_820_p2 == 1'd0) & (tmp_4_fu_814_p2 == 1'd0) & (tmp_3_fu_808_p2 == 1'd0))) begin
        tmp_7_reg_1216 <= tmp_7_fu_832_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_802_p2 == 1'd1) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1) & (tmp_7_fu_832_p2 == 1'd0) & (tmp_6_fu_826_p2 == 1'd0) & (tmp_5_fu_820_p2 == 1'd0) & (tmp_4_fu_814_p2 == 1'd0) & (tmp_3_fu_808_p2 == 1'd0))) begin
        tmp_8_reg_1220 <= tmp_8_fu_838_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_802_p2 == 1'd1) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1) & (tmp_8_fu_838_p2 == 1'd0) & (tmp_7_fu_832_p2 == 1'd0) & (tmp_6_fu_826_p2 == 1'd0) & (tmp_5_fu_820_p2 == 1'd0) & (tmp_4_fu_814_p2 == 1'd0) & (tmp_3_fu_808_p2 == 1'd0))) begin
        tmp_9_reg_1224 <= tmp_9_fu_844_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_802_p2 == 1'd1) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1) & (tmp_9_fu_844_p2 == 1'd0) & (tmp_8_fu_838_p2 == 1'd0) & (tmp_7_fu_832_p2 == 1'd0) & (tmp_6_fu_826_p2 == 1'd0) & (tmp_5_fu_820_p2 == 1'd0) & (tmp_4_fu_814_p2 == 1'd0) & (tmp_3_fu_808_p2 == 1'd0))) begin
        tmp_s_reg_1228 <= tmp_s_fu_850_p2;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_reg_1196 == 1'd1) & (icmp_reg_1192 == 1'd1) & (empty_n_1_reg_1155 == 1'd1) & (tmp_12_reg_1240 == 1'd0) & (tmp_11_reg_1236 == 1'd0) & (tmp_10_reg_1232 == 1'd0) & (tmp_s_reg_1228 == 1'd0) & (tmp_9_reg_1224 == 1'd0) & (tmp_8_reg_1220 == 1'd0) & (tmp_7_reg_1216 == 1'd0) & (tmp_6_reg_1212 == 1'd0) & (tmp_5_reg_1208 == 1'd0) & (tmp_4_reg_1204 == 1'd0) & (tmp_3_reg_1200 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_state_s_phi_fu_676_p30 = p_s_fu_879_p3;
    end else begin
        ap_phi_mux_state_s_phi_fu_676_p30 = ap_phi_reg_pp0_iter1_state_s_reg_659;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_31_reg_1292 == 1'd1) & (tmp_30_reg_1288 == 1'd0) & (tmp_29_reg_1284 == 1'd0) & (tmp_28_reg_1280 == 1'd0) & (tmp_27_reg_1276 == 1'd0) & (tmp_23_reg_1272 == 1'd0) & (tmp_22_reg_1268 == 1'd0) & (tmp_21_reg_1264 == 1'd0) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        app_commit_write_buf_V_blk_n = app_commit_write_buf_V_full_n;
    end else begin
        app_commit_write_buf_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op180_write_state4 == 1'b1))) begin
        app_commit_write_buf_V_write = 1'b1;
    end else begin
        app_commit_write_buf_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (app_file_infos_0_V_full_n == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_23_fu_930_p2 == 1'd1) & (tmp_22_fu_924_p2 == 1'd0) & (tmp_21_fu_918_p2 == 1'd0) & (tmp_20_fu_912_p2 == 1'd0) & (tmp_18_fu_906_p2 == 1'd0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0))) begin
        app_file_infos_0_V_write = 1'b1;
    end else begin
        app_file_infos_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (app_file_infos_1_V_full_n == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_23_fu_930_p2 == 1'd1) & (tmp_22_fu_924_p2 == 1'd0) & (tmp_21_fu_918_p2 == 1'd0) & (tmp_20_fu_912_p2 == 1'd0) & (tmp_18_fu_906_p2 == 1'd0) & (tmp_17_fu_900_p2 == 1'd0) & (tmp_15_fu_894_p2 == 1'd0) & (tmp_14_fu_888_p2 == 1'd0))) begin
        app_file_infos_1_V_write = 1'b1;
    end else begin
        app_file_infos_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_28_reg_1280 == 1'd1) & (tmp_27_reg_1276 == 1'd0) & (tmp_23_reg_1272 == 1'd0) & (tmp_22_reg_1268 == 1'd0) & (tmp_21_reg_1264 == 1'd0) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        app_free_buf_V_blk_n = app_free_buf_V_full_n;
    end else begin
        app_free_buf_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op183_write_state4 == 1'b1))) begin
        app_free_buf_V_write = 1'b1;
    end else begin
        app_free_buf_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_29_reg_1284 == 1'd1) & (tmp_28_reg_1280 == 1'd0) & (tmp_27_reg_1276 == 1'd0) & (tmp_23_reg_1272 == 1'd0) & (tmp_22_reg_1268 == 1'd0) & (tmp_21_reg_1264 == 1'd0) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        app_input_params_V_blk_n = app_input_params_V_full_n;
    end else begin
        app_input_params_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op182_write_state4 == 1'b1))) begin
        app_input_params_V_write = 1'b1;
    end else begin
        app_input_params_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_33_reg_1300 == 1'd1) & (tmp_32_reg_1296 == 1'd0) & (tmp_31_reg_1292 == 1'd0) & (tmp_30_reg_1288 == 1'd0) & (tmp_29_reg_1284 == 1'd0) & (tmp_28_reg_1280 == 1'd0) & (tmp_27_reg_1276 == 1'd0) & (tmp_23_reg_1272 == 1'd0) & (tmp_22_reg_1268 == 1'd0) & (tmp_21_reg_1264 == 1'd0) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        app_is_write_mode_0_V_blk_n = app_is_write_mode_0_V_full_n;
    end else begin
        app_is_write_mode_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op167_write_state4 == 1'b1))) begin
        app_is_write_mode_0_V_write = 1'b1;
    end else begin
        app_is_write_mode_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_33_reg_1300 == 1'd1) & (tmp_32_reg_1296 == 1'd0) & (tmp_31_reg_1292 == 1'd0) & (tmp_30_reg_1288 == 1'd0) & (tmp_29_reg_1284 == 1'd0) & (tmp_28_reg_1280 == 1'd0) & (tmp_27_reg_1276 == 1'd0) & (tmp_23_reg_1272 == 1'd0) & (tmp_22_reg_1268 == 1'd0) & (tmp_21_reg_1264 == 1'd0) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        app_is_write_mode_1_V_blk_n = app_is_write_mode_1_V_full_n;
    end else begin
        app_is_write_mode_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op167_write_state4 == 1'b1))) begin
        app_is_write_mode_1_V_write = 1'b1;
    end else begin
        app_is_write_mode_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_33_reg_1300 == 1'd1) & (tmp_32_reg_1296 == 1'd0) & (tmp_31_reg_1292 == 1'd0) & (tmp_30_reg_1288 == 1'd0) & (tmp_29_reg_1284 == 1'd0) & (tmp_28_reg_1280 == 1'd0) & (tmp_27_reg_1276 == 1'd0) & (tmp_23_reg_1272 == 1'd0) & (tmp_22_reg_1268 == 1'd0) & (tmp_21_reg_1264 == 1'd0) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        app_is_write_mode_2_V_blk_n = app_is_write_mode_2_V_full_n;
    end else begin
        app_is_write_mode_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op167_write_state4 == 1'b1))) begin
        app_is_write_mode_2_V_write = 1'b1;
    end else begin
        app_is_write_mode_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (has_half_write_total_len_load_reg_1304 == 1'd1) & (tmp_32_reg_1296 == 1'd1) & (tmp_31_reg_1292 == 1'd0) & (tmp_30_reg_1288 == 1'd0) & (tmp_29_reg_1284 == 1'd0) & (tmp_28_reg_1280 == 1'd0) & (tmp_27_reg_1276 == 1'd0) & (tmp_23_reg_1272 == 1'd0) & (tmp_22_reg_1268 == 1'd0) & (tmp_21_reg_1264 == 1'd0) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        app_write_total_len_V_blk_n = app_write_total_len_V_full_n;
    end else begin
        app_write_total_len_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op178_write_state4 == 1'b1))) begin
        app_write_total_len_V_write = 1'b1;
    end else begin
        app_write_total_len_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_21_reg_1264 == 1'd1) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        device_read_delay_cycle_cnts_V_blk_n = device_read_delay_cycle_cnts_V_full_n;
    end else begin
        device_read_delay_cycle_cnts_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op188_write_state4 == 1'b1))) begin
        device_read_delay_cycle_cnts_V_write = 1'b1;
    end else begin
        device_read_delay_cycle_cnts_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_21_reg_1264 == 1'd1) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        device_write_delay_cycle_cnts_V_blk_n = device_write_delay_cycle_cnts_V_full_n;
    end else begin
        device_write_delay_cycle_cnts_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op188_write_state4 == 1'b1))) begin
        device_write_delay_cycle_cnts_V_write = 1'b1;
    end else begin
        device_write_delay_cycle_cnts_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (is_read_host_throttle_params_load_reg_1312 == 1'd1) & (tmp_20_reg_1260 == 1'd1) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        dma_read_throttle_params_V_blk_n = dma_read_throttle_params_V_full_n;
    end else begin
        dma_read_throttle_params_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op191_write_state4 == 1'b1))) begin
        dma_read_throttle_params_V_write = 1'b1;
    end else begin
        dma_read_throttle_params_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_20_reg_1260 == 1'd1) & (is_read_host_throttle_params_load_reg_1312 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        dma_write_throttle_params_V_blk_n = dma_write_throttle_params_V_full_n;
    end else begin
        dma_write_throttle_params_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op190_write_state4 == 1'b1))) begin
        dma_write_throttle_params_V_write = 1'b1;
    end else begin
        dma_write_throttle_params_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (is_read_device_throttle_params_load_reg_1308 == 1'd1) & (tmp_22_reg_1268 == 1'd1) & (tmp_21_reg_1264 == 1'd0) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        drive_read_throttle_params_V_blk_n = drive_read_throttle_params_V_full_n;
    end else begin
        drive_read_throttle_params_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op187_write_state4 == 1'b1))) begin
        drive_read_throttle_params_V_write = 1'b1;
    end else begin
        drive_read_throttle_params_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_22_reg_1268 == 1'd1) & (is_read_device_throttle_params_load_reg_1308 == 1'd0) & (tmp_21_reg_1264 == 1'd0) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        drive_write_throttle_params_V_blk_n = drive_write_throttle_params_V_full_n;
    end else begin
        drive_write_throttle_params_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op186_write_state4 == 1'b1))) begin
        drive_write_throttle_params_V_write = 1'b1;
    end else begin
        drive_write_throttle_params_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_18_reg_1256 == 1'd1) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        kbuf_addrs_V_blk_n = kbuf_addrs_V_full_n;
    end else begin
        kbuf_addrs_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op192_write_state4 == 1'b1))) begin
        kbuf_addrs_V_write = 1'b1;
    end else begin
        kbuf_addrs_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & ((poke_V_tag_empty_n & poke_V_data_empty_n) == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        poke_V_tag0_update = 1'b1;
    end else begin
        poke_V_tag0_update = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_27_reg_1276 == 1'd1) & (tmp_23_reg_1272 == 1'd0) & (tmp_22_reg_1268 == 1'd0) & (tmp_21_reg_1264 == 1'd0) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        read_mode_app_buf_addrs_V_blk_n = read_mode_app_buf_addrs_V_full_n;
    end else begin
        read_mode_app_buf_addrs_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op184_write_state4 == 1'b1))) begin
        read_mode_app_buf_addrs_V_write = 1'b1;
    end else begin
        read_mode_app_buf_addrs_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op212_write_state4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op202_write_state4 == 1'b1)))) begin
        reqs_incoming_V_rw1_update = 1'b1;
    end else begin
        reqs_incoming_V_rw1_update = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_17_reg_1252 == 1'd1) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_15_reg_1248 == 1'd1) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0)))) begin
        reqs_incoming_V_rw_blk_n = reqs_incoming_V_rw_full_n;
    end else begin
        reqs_incoming_V_rw_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op212_write_state4 == 1'b1)) begin
            reqs_incoming_V_rw_din = 1'd1;
        end else if ((ap_predicate_op202_write_state4 == 1'b1)) begin
            reqs_incoming_V_rw_din = 1'd0;
        end else begin
            reqs_incoming_V_rw_din = 'bx;
        end
    end else begin
        reqs_incoming_V_rw_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_17_reg_1252 == 1'd1) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_15_reg_1248 == 1'd1) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0)))) begin
        reqs_incoming_V_sector_num_blk_n = reqs_incoming_V_sector_num_full_n;
    end else begin
        reqs_incoming_V_sector_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op212_write_state4 == 1'b1)) begin
            reqs_incoming_V_sector_num_din = tmp_sector_num_1_fu_1106_p1;
        end else if ((ap_predicate_op202_write_state4 == 1'b1)) begin
            reqs_incoming_V_sector_num_din = tmp_sector_num_3_fu_1072_p1;
        end else begin
            reqs_incoming_V_sector_num_din = 'bx;
        end
    end else begin
        reqs_incoming_V_sector_num_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_17_reg_1252 == 1'd1) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_15_reg_1248 == 1'd1) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0)))) begin
        reqs_incoming_V_sector_off_blk_n = reqs_incoming_V_sector_off_full_n;
    end else begin
        reqs_incoming_V_sector_off_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op212_write_state4 == 1'b1)) begin
            reqs_incoming_V_sector_off_din = req_sector_off_4_fu_1092_p1;
        end else if ((ap_predicate_op202_write_state4 == 1'b1)) begin
            reqs_incoming_V_sector_off_din = req_sector_off_5_fu_1058_p1;
        end else begin
            reqs_incoming_V_sector_off_din = 'bx;
        end
    end else begin
        reqs_incoming_V_sector_off_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_17_reg_1252 == 1'd1) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_15_reg_1248 == 1'd1) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0)))) begin
        reqs_incoming_V_tag_blk_n = reqs_incoming_V_tag_full_n;
    end else begin
        reqs_incoming_V_tag_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op212_write_state4 == 1'b1)) begin
            reqs_incoming_V_tag_din = tmp_tag_1_fu_1121_p1;
        end else if ((ap_predicate_op202_write_state4 == 1'b1)) begin
            reqs_incoming_V_tag_din = tmp_tag_3_fu_1087_p1;
        end else begin
            reqs_incoming_V_tag_din = 'bx;
        end
    end else begin
        reqs_incoming_V_tag_din = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_30_reg_1288 == 1'd1) & (tmp_29_reg_1284 == 1'd0) & (tmp_28_reg_1280 == 1'd0) & (tmp_27_reg_1276 == 1'd0) & (tmp_23_reg_1272 == 1'd0) & (tmp_22_reg_1268 == 1'd0) & (tmp_21_reg_1264 == 1'd0) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        reset_sigs_V_blk_n = reset_sigs_V_full_n;
    end else begin
        reset_sigs_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op181_write_state4 == 1'b1))) begin
        reset_sigs_V_write = 1'b1;
    end else begin
        reset_sigs_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_27_reg_1276 == 1'd1) & (tmp_23_reg_1272 == 1'd0) & (tmp_22_reg_1268 == 1'd0) & (tmp_21_reg_1264 == 1'd0) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        write_mode_app_buf_addrs_V_blk_n = write_mode_app_buf_addrs_V_full_n;
    end else begin
        write_mode_app_buf_addrs_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op184_write_state4 == 1'b1))) begin
        write_mode_app_buf_addrs_V_write = 1'b1;
    end else begin
        write_mode_app_buf_addrs_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (((reqs_incoming_V_rw1_status == 1'b0) & (ap_predicate_op212_write_state4 == 1'b1)) | ((reqs_incoming_V_rw1_status == 1'b0) & (ap_predicate_op202_write_state4 == 1'b1)) | ((kbuf_addrs_V_full_n == 1'b0) & (ap_predicate_op192_write_state4 == 1'b1)) | ((dma_read_throttle_params_V_full_n == 1'b0) & (ap_predicate_op191_write_state4 == 1'b1)) | ((dma_write_throttle_params_V_full_n == 1'b0) & (ap_predicate_op190_write_state4 == 1'b1)) | ((device_write_delay_cycle_cnts_V_full_n == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1)) | ((device_read_delay_cycle_cnts_V_full_n == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1)) | ((drive_read_throttle_params_V_full_n == 1'b0) & (ap_predicate_op187_write_state4 == 1'b1)) | ((drive_write_throttle_params_V_full_n == 1'b0) & (ap_predicate_op186_write_state4 == 1'b1)) | ((write_mode_app_buf_addrs_V_full_n == 1'b0) & (ap_predicate_op184_write_state4 == 1'b1)) | ((read_mode_app_buf_addrs_V_full_n == 1'b0) & (ap_predicate_op184_write_state4 == 1'b1)) | ((app_free_buf_V_full_n == 1'b0) & (ap_predicate_op183_write_state4 == 1'b1)) | ((app_input_params_V_full_n == 1'b0) & (ap_predicate_op182_write_state4 == 1'b1)) | ((reset_sigs_V_full_n == 1'b0) & (ap_predicate_op181_write_state4 == 1'b1)) | ((app_commit_write_buf_V_full_n == 1'b0) & (ap_predicate_op180_write_state4 == 1'b1)) | ((app_write_total_len_V_full_n == 1'b0) & (ap_predicate_op178_write_state4 == 1'b1)) | ((app_is_write_mode_2_V_full_n == 1'b0) & (ap_predicate_op167_write_state4 == 1'b1)) | ((app_is_write_mode_1_V_full_n == 1'b0) & (ap_predicate_op167_write_state4 == 1'b1)) | ((app_is_write_mode_0_V_full_n == 1'b0) & (ap_predicate_op167_write_state4 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (((reqs_incoming_V_rw1_status == 1'b0) & (ap_predicate_op212_write_state4 == 1'b1)) | ((reqs_incoming_V_rw1_status == 1'b0) & (ap_predicate_op202_write_state4 == 1'b1)) | ((kbuf_addrs_V_full_n == 1'b0) & (ap_predicate_op192_write_state4 == 1'b1)) | ((dma_read_throttle_params_V_full_n == 1'b0) & (ap_predicate_op191_write_state4 == 1'b1)) | ((dma_write_throttle_params_V_full_n == 1'b0) & (ap_predicate_op190_write_state4 == 1'b1)) | ((device_write_delay_cycle_cnts_V_full_n == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1)) | ((device_read_delay_cycle_cnts_V_full_n == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1)) | ((drive_read_throttle_params_V_full_n == 1'b0) & (ap_predicate_op187_write_state4 == 1'b1)) | ((drive_write_throttle_params_V_full_n == 1'b0) & (ap_predicate_op186_write_state4 == 1'b1)) | ((write_mode_app_buf_addrs_V_full_n == 1'b0) & (ap_predicate_op184_write_state4 == 1'b1)) | ((read_mode_app_buf_addrs_V_full_n == 1'b0) & (ap_predicate_op184_write_state4 == 1'b1)) | ((app_free_buf_V_full_n == 1'b0) & (ap_predicate_op183_write_state4 == 1'b1)) | ((app_input_params_V_full_n == 1'b0) & (ap_predicate_op182_write_state4 == 1'b1)) | ((reset_sigs_V_full_n == 1'b0) & (ap_predicate_op181_write_state4 == 1'b1)) | ((app_commit_write_buf_V_full_n == 1'b0) & (ap_predicate_op180_write_state4 == 1'b1)) | ((app_write_total_len_V_full_n == 1'b0) & (ap_predicate_op178_write_state4 == 1'b1)) | ((app_is_write_mode_2_V_full_n == 1'b0) & (ap_predicate_op167_write_state4 == 1'b1)) | ((app_is_write_mode_1_V_full_n == 1'b0) & (ap_predicate_op167_write_state4 == 1'b1)) | ((app_is_write_mode_0_V_full_n == 1'b0) & (ap_predicate_op167_write_state4 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (((reqs_incoming_V_rw1_status == 1'b0) & (ap_predicate_op212_write_state4 == 1'b1)) | ((reqs_incoming_V_rw1_status == 1'b0) & (ap_predicate_op202_write_state4 == 1'b1)) | ((kbuf_addrs_V_full_n == 1'b0) & (ap_predicate_op192_write_state4 == 1'b1)) | ((dma_read_throttle_params_V_full_n == 1'b0) & (ap_predicate_op191_write_state4 == 1'b1)) | ((dma_write_throttle_params_V_full_n == 1'b0) & (ap_predicate_op190_write_state4 == 1'b1)) | ((device_write_delay_cycle_cnts_V_full_n == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1)) | ((device_read_delay_cycle_cnts_V_full_n == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1)) | ((drive_read_throttle_params_V_full_n == 1'b0) & (ap_predicate_op187_write_state4 == 1'b1)) | ((drive_write_throttle_params_V_full_n == 1'b0) & (ap_predicate_op186_write_state4 == 1'b1)) | ((write_mode_app_buf_addrs_V_full_n == 1'b0) & (ap_predicate_op184_write_state4 == 1'b1)) | ((read_mode_app_buf_addrs_V_full_n == 1'b0) & (ap_predicate_op184_write_state4 == 1'b1)) | ((app_free_buf_V_full_n == 1'b0) & (ap_predicate_op183_write_state4 == 1'b1)) | ((app_input_params_V_full_n == 1'b0) & (ap_predicate_op182_write_state4 == 1'b1)) | ((reset_sigs_V_full_n == 1'b0) & (ap_predicate_op181_write_state4 == 1'b1)) | ((app_commit_write_buf_V_full_n == 1'b0) & (ap_predicate_op180_write_state4 == 1'b1)) | ((app_write_total_len_V_full_n == 1'b0) & (ap_predicate_op178_write_state4 == 1'b1)) | ((app_is_write_mode_2_V_full_n == 1'b0) & (ap_predicate_op167_write_state4 == 1'b1)) | ((app_is_write_mode_1_V_full_n == 1'b0) & (ap_predicate_op167_write_state4 == 1'b1)) | ((app_is_write_mode_0_V_full_n == 1'b0) & (ap_predicate_op167_write_state4 == 1'b1))));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = (((reqs_incoming_V_rw1_status == 1'b0) & (ap_predicate_op212_write_state4 == 1'b1)) | ((reqs_incoming_V_rw1_status == 1'b0) & (ap_predicate_op202_write_state4 == 1'b1)) | ((kbuf_addrs_V_full_n == 1'b0) & (ap_predicate_op192_write_state4 == 1'b1)) | ((dma_read_throttle_params_V_full_n == 1'b0) & (ap_predicate_op191_write_state4 == 1'b1)) | ((dma_write_throttle_params_V_full_n == 1'b0) & (ap_predicate_op190_write_state4 == 1'b1)) | ((device_write_delay_cycle_cnts_V_full_n == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1)) | ((device_read_delay_cycle_cnts_V_full_n == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1)) | ((drive_read_throttle_params_V_full_n == 1'b0) & (ap_predicate_op187_write_state4 == 1'b1)) | ((drive_write_throttle_params_V_full_n == 1'b0) & (ap_predicate_op186_write_state4 == 1'b1)) | ((write_mode_app_buf_addrs_V_full_n == 1'b0) & (ap_predicate_op184_write_state4 == 1'b1)) | ((read_mode_app_buf_addrs_V_full_n == 1'b0) & (ap_predicate_op184_write_state4 == 1'b1)) | ((app_free_buf_V_full_n == 1'b0) & (ap_predicate_op183_write_state4 == 1'b1)) | ((app_input_params_V_full_n == 1'b0) & (ap_predicate_op182_write_state4 == 1'b1)) | ((reset_sigs_V_full_n == 1'b0) & (ap_predicate_op181_write_state4 == 1'b1)) | ((app_commit_write_buf_V_full_n == 1'b0) & (ap_predicate_op180_write_state4 == 1'b1)) | ((app_write_total_len_V_full_n == 1'b0) & (ap_predicate_op178_write_state4 == 1'b1)) | ((app_is_write_mode_2_V_full_n == 1'b0) & (ap_predicate_op167_write_state4 == 1'b1)) | ((app_is_write_mode_1_V_full_n == 1'b0) & (ap_predicate_op167_write_state4 == 1'b1)) | ((app_is_write_mode_0_V_full_n == 1'b0) & (ap_predicate_op167_write_state4 == 1'b1)));
end

always @ (*) begin
    ap_condition_571 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_581 = ((icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1) & (icmp3_fu_802_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_587 = ((tmp_3_fu_808_p2 == 1'd1) & (icmp3_fu_802_p2 == 1'd1) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1));
end

always @ (*) begin
    ap_condition_594 = ((tmp_4_fu_814_p2 == 1'd1) & (icmp3_fu_802_p2 == 1'd1) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1) & (tmp_3_fu_808_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_602 = ((tmp_5_fu_820_p2 == 1'd1) & (icmp3_fu_802_p2 == 1'd1) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1) & (tmp_4_fu_814_p2 == 1'd0) & (tmp_3_fu_808_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_611 = ((tmp_6_fu_826_p2 == 1'd1) & (icmp3_fu_802_p2 == 1'd1) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1) & (tmp_5_fu_820_p2 == 1'd0) & (tmp_4_fu_814_p2 == 1'd0) & (tmp_3_fu_808_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_621 = ((tmp_7_fu_832_p2 == 1'd1) & (icmp3_fu_802_p2 == 1'd1) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1) & (tmp_6_fu_826_p2 == 1'd0) & (tmp_5_fu_820_p2 == 1'd0) & (tmp_4_fu_814_p2 == 1'd0) & (tmp_3_fu_808_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_632 = ((tmp_8_fu_838_p2 == 1'd1) & (icmp3_fu_802_p2 == 1'd1) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1) & (tmp_7_fu_832_p2 == 1'd0) & (tmp_6_fu_826_p2 == 1'd0) & (tmp_5_fu_820_p2 == 1'd0) & (tmp_4_fu_814_p2 == 1'd0) & (tmp_3_fu_808_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_644 = ((tmp_9_fu_844_p2 == 1'd1) & (icmp3_fu_802_p2 == 1'd1) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1) & (tmp_8_fu_838_p2 == 1'd0) & (tmp_7_fu_832_p2 == 1'd0) & (tmp_6_fu_826_p2 == 1'd0) & (tmp_5_fu_820_p2 == 1'd0) & (tmp_4_fu_814_p2 == 1'd0) & (tmp_3_fu_808_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_657 = ((tmp_s_fu_850_p2 == 1'd1) & (icmp3_fu_802_p2 == 1'd1) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1) & (tmp_9_fu_844_p2 == 1'd0) & (tmp_8_fu_838_p2 == 1'd0) & (tmp_7_fu_832_p2 == 1'd0) & (tmp_6_fu_826_p2 == 1'd0) & (tmp_5_fu_820_p2 == 1'd0) & (tmp_4_fu_814_p2 == 1'd0) & (tmp_3_fu_808_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_671 = ((tmp_10_fu_856_p2 == 1'd1) & (icmp3_fu_802_p2 == 1'd1) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1) & (tmp_s_fu_850_p2 == 1'd0) & (tmp_9_fu_844_p2 == 1'd0) & (tmp_8_fu_838_p2 == 1'd0) & (tmp_7_fu_832_p2 == 1'd0) & (tmp_6_fu_826_p2 == 1'd0) & (tmp_5_fu_820_p2 == 1'd0) & (tmp_4_fu_814_p2 == 1'd0) & (tmp_3_fu_808_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_686 = ((tmp_11_fu_862_p2 == 1'd1) & (icmp3_fu_802_p2 == 1'd1) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1) & (tmp_10_fu_856_p2 == 1'd0) & (tmp_s_fu_850_p2 == 1'd0) & (tmp_9_fu_844_p2 == 1'd0) & (tmp_8_fu_838_p2 == 1'd0) & (tmp_7_fu_832_p2 == 1'd0) & (tmp_6_fu_826_p2 == 1'd0) & (tmp_5_fu_820_p2 == 1'd0) & (tmp_4_fu_814_p2 == 1'd0) & (tmp_3_fu_808_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_702 = ((tmp_12_fu_868_p2 == 1'd1) & (icmp3_fu_802_p2 == 1'd1) & (icmp_fu_786_p2 == 1'd1) & (empty_n_1_fu_760_p1 == 1'd1) & (tmp_11_fu_862_p2 == 1'd0) & (tmp_10_fu_856_p2 == 1'd0) & (tmp_s_fu_850_p2 == 1'd0) & (tmp_9_fu_844_p2 == 1'd0) & (tmp_8_fu_838_p2 == 1'd0) & (tmp_7_fu_832_p2 == 1'd0) & (tmp_6_fu_826_p2 == 1'd0) & (tmp_5_fu_820_p2 == 1'd0) & (tmp_4_fu_814_p2 == 1'd0) & (tmp_3_fu_808_p2 == 1'd0));
end

assign ap_done = 1'b0;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_state_s_reg_659 = 'bx;

always @ (*) begin
    ap_predicate_op167_write_state4 = ((tmp_33_reg_1300 == 1'd1) & (tmp_32_reg_1296 == 1'd0) & (tmp_31_reg_1292 == 1'd0) & (tmp_30_reg_1288 == 1'd0) & (tmp_29_reg_1284 == 1'd0) & (tmp_28_reg_1280 == 1'd0) & (tmp_27_reg_1276 == 1'd0) & (tmp_23_reg_1272 == 1'd0) & (tmp_22_reg_1268 == 1'd0) & (tmp_21_reg_1264 == 1'd0) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0));
end

always @ (*) begin
    ap_predicate_op178_write_state4 = ((has_half_write_total_len_load_reg_1304 == 1'd1) & (tmp_32_reg_1296 == 1'd1) & (tmp_31_reg_1292 == 1'd0) & (tmp_30_reg_1288 == 1'd0) & (tmp_29_reg_1284 == 1'd0) & (tmp_28_reg_1280 == 1'd0) & (tmp_27_reg_1276 == 1'd0) & (tmp_23_reg_1272 == 1'd0) & (tmp_22_reg_1268 == 1'd0) & (tmp_21_reg_1264 == 1'd0) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0));
end

always @ (*) begin
    ap_predicate_op180_write_state4 = ((tmp_31_reg_1292 == 1'd1) & (tmp_30_reg_1288 == 1'd0) & (tmp_29_reg_1284 == 1'd0) & (tmp_28_reg_1280 == 1'd0) & (tmp_27_reg_1276 == 1'd0) & (tmp_23_reg_1272 == 1'd0) & (tmp_22_reg_1268 == 1'd0) & (tmp_21_reg_1264 == 1'd0) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0));
end

always @ (*) begin
    ap_predicate_op181_write_state4 = ((tmp_30_reg_1288 == 1'd1) & (tmp_29_reg_1284 == 1'd0) & (tmp_28_reg_1280 == 1'd0) & (tmp_27_reg_1276 == 1'd0) & (tmp_23_reg_1272 == 1'd0) & (tmp_22_reg_1268 == 1'd0) & (tmp_21_reg_1264 == 1'd0) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0));
end

always @ (*) begin
    ap_predicate_op182_write_state4 = ((tmp_29_reg_1284 == 1'd1) & (tmp_28_reg_1280 == 1'd0) & (tmp_27_reg_1276 == 1'd0) & (tmp_23_reg_1272 == 1'd0) & (tmp_22_reg_1268 == 1'd0) & (tmp_21_reg_1264 == 1'd0) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0));
end

always @ (*) begin
    ap_predicate_op183_write_state4 = ((tmp_28_reg_1280 == 1'd1) & (tmp_27_reg_1276 == 1'd0) & (tmp_23_reg_1272 == 1'd0) & (tmp_22_reg_1268 == 1'd0) & (tmp_21_reg_1264 == 1'd0) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0));
end

always @ (*) begin
    ap_predicate_op184_write_state4 = ((tmp_27_reg_1276 == 1'd1) & (tmp_23_reg_1272 == 1'd0) & (tmp_22_reg_1268 == 1'd0) & (tmp_21_reg_1264 == 1'd0) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0));
end

always @ (*) begin
    ap_predicate_op186_write_state4 = ((tmp_22_reg_1268 == 1'd1) & (is_read_device_throttle_params_load_reg_1308 == 1'd0) & (tmp_21_reg_1264 == 1'd0) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0));
end

always @ (*) begin
    ap_predicate_op187_write_state4 = ((is_read_device_throttle_params_load_reg_1308 == 1'd1) & (tmp_22_reg_1268 == 1'd1) & (tmp_21_reg_1264 == 1'd0) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0));
end

always @ (*) begin
    ap_predicate_op188_write_state4 = ((tmp_21_reg_1264 == 1'd1) & (tmp_20_reg_1260 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0));
end

always @ (*) begin
    ap_predicate_op190_write_state4 = ((tmp_20_reg_1260 == 1'd1) & (is_read_host_throttle_params_load_reg_1312 == 1'd0) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0));
end

always @ (*) begin
    ap_predicate_op191_write_state4 = ((is_read_host_throttle_params_load_reg_1312 == 1'd1) & (tmp_20_reg_1260 == 1'd1) & (tmp_18_reg_1256 == 1'd0) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0));
end

always @ (*) begin
    ap_predicate_op192_write_state4 = ((tmp_18_reg_1256 == 1'd1) & (tmp_17_reg_1252 == 1'd0) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0));
end

always @ (*) begin
    ap_predicate_op202_write_state4 = ((tmp_17_reg_1252 == 1'd1) & (tmp_15_reg_1248 == 1'd0) & (tmp_14_reg_1244 == 1'd0));
end

always @ (*) begin
    ap_predicate_op212_write_state4 = ((tmp_15_reg_1248 == 1'd1) & (tmp_14_reg_1244 == 1'd0));
end

assign ap_ready = 1'b0;

assign app_commit_write_buf_V_din = ap_reg_pp0_iter1_tmp_data_reg_1165;

assign app_file_infos_0_V_din = tmp_data_reg_1165;

assign app_file_infos_1_V_din = tmp_data_reg_1165;

assign app_free_buf_V_din = 1'd0;

assign app_input_params_V_din = ap_reg_pp0_iter1_tmp_data_reg_1165;

assign app_is_write_mode_0_V_din = tmp_38_fu_1002_p2;

assign app_is_write_mode_1_V_din = tmp_38_fu_1002_p2;

assign app_is_write_mode_2_V_din = tmp_38_fu_1002_p2;

assign app_write_total_len_V_din = {{tmp_36_fu_1034_p4}, {tmp_35_fu_1029_p2}};

assign device_read_delay_cycle_cnts_V_din = ap_reg_pp0_iter1_tmp_data_reg_1165;

assign device_write_delay_cycle_cnts_V_din = ap_reg_pp0_iter1_tmp_data_reg_1165;

assign dma_read_throttle_params_V_din = ap_reg_pp0_iter1_tmp_data_reg_1165;

assign dma_write_throttle_params_V_din = ap_reg_pp0_iter1_tmp_data_reg_1165;

assign drive_read_throttle_params_V_din = ap_reg_pp0_iter1_tmp_data_reg_1165;

assign drive_write_throttle_params_V_din = ap_reg_pp0_iter1_tmp_data_reg_1165;

assign empty_n_1_fu_760_p1 = empty_n_nbread_fu_498_p3_0;

assign empty_n_nbread_fu_498_p3_0 = (poke_V_tag_empty_n & poke_V_data_empty_n);

assign grp_fu_737_p4 = {{ap_reg_pp0_iter1_tmp_data_reg_1165[31:3]}};

assign grp_fu_746_p4 = {{ap_reg_pp0_iter1_tmp_tag_4_reg_1159[31:2]}};

assign has_half_write_total_len_load_load_fu_978_p1 = has_half_write_total_len_fu_482;

assign icmp3_fu_802_p2 = ((tmp_24_fu_792_p4 == 24'd0) ? 1'b1 : 1'b0);

assign icmp_fu_786_p2 = ((tmp_16_fu_776_p4 == 23'd0) ? 1'b1 : 1'b0);

assign is_read_device_throttle_params_load_load_fu_986_p1 = is_read_device_throttle_params_fu_486;

assign is_read_host_throttle_params_load_load_fu_994_p1 = is_read_host_throttle_params_fu_490;

assign kbuf_addrs_V_din = ap_reg_pp0_iter1_tmp_data_reg_1165;

assign p_s_fu_879_p3 = ((tmp_13_fu_874_p2[0:0] === 1'b1) ? 5'd16 : 5'd0);

assign poke_V_data_read = poke_V_tag0_update;

assign poke_V_tag_read = poke_V_tag0_update;

assign read_mode_app_buf_addrs_V_din = ap_reg_pp0_iter1_tmp_data_reg_1165;

assign req_sector_num_1_fu_1066_p2 = (tmp_19_cast_fu_1063_p1 + 4'd1);

assign req_sector_num_fu_1100_p2 = (tmp_16_cast_fu_1097_p1 + 4'd1);

assign req_sector_off_4_fu_1092_p1 = grp_fu_737_p4;

assign req_sector_off_5_fu_1058_p1 = grp_fu_737_p4;

assign req_tag_1_fu_1081_p2 = ($signed(tmp_20_cast_fu_1077_p1) + $signed(31'd2147483584));

assign req_tag_fu_1115_p2 = ($signed(tmp_17_cast_fu_1111_p1) + $signed(31'd2147483520));

assign reqs_incoming_V_rw1_status = (reqs_incoming_V_tag_full_n & reqs_incoming_V_sector_off_full_n & reqs_incoming_V_sector_num_full_n & reqs_incoming_V_rw_full_n);

assign reqs_incoming_V_rw_write = reqs_incoming_V_rw1_update;

assign reqs_incoming_V_sector_num_write = reqs_incoming_V_rw1_update;

assign reqs_incoming_V_sector_off_write = reqs_incoming_V_rw1_update;

assign reqs_incoming_V_tag_write = reqs_incoming_V_rw1_update;

assign reset_sigs_V_din = 1'd0;

assign tmp_10_fu_856_p2 = ((poke_V_tag_dout == 32'd56) ? 1'b1 : 1'b0);

assign tmp_11_fu_862_p2 = ((poke_V_tag_dout == 32'd64) ? 1'b1 : 1'b0);

assign tmp_12_fu_868_p2 = ((poke_V_tag_dout == 32'd68) ? 1'b1 : 1'b0);

assign tmp_13_fu_874_p2 = ((tmp_tag_4_reg_1159 == 32'd72) ? 1'b1 : 1'b0);

assign tmp_14_fu_888_p2 = ((ap_phi_mux_state_s_phi_fu_676_p30 == 5'd0) ? 1'b1 : 1'b0);

assign tmp_15_fu_894_p2 = ((ap_phi_mux_state_s_phi_fu_676_p30 == 5'd1) ? 1'b1 : 1'b0);

assign tmp_16_cast_fu_1097_p1 = ap_reg_pp0_iter1_tmp_2_reg_1186;

assign tmp_16_fu_776_p4 = {{poke_V_tag_dout[31:9]}};

assign tmp_17_cast_fu_1111_p1 = grp_fu_746_p4;

assign tmp_17_fu_900_p2 = ((ap_phi_mux_state_s_phi_fu_676_p30 == 5'd2) ? 1'b1 : 1'b0);

assign tmp_18_fu_906_p2 = ((ap_phi_mux_state_s_phi_fu_676_p30 == 5'd3) ? 1'b1 : 1'b0);

assign tmp_19_cast_fu_1063_p1 = ap_reg_pp0_iter1_tmp_2_reg_1186;

assign tmp_20_cast_fu_1077_p1 = grp_fu_746_p4;

assign tmp_20_fu_912_p2 = ((ap_phi_mux_state_s_phi_fu_676_p30 == 5'd5) ? 1'b1 : 1'b0);

assign tmp_21_fu_918_p2 = ((ap_phi_mux_state_s_phi_fu_676_p30 == 5'd6) ? 1'b1 : 1'b0);

assign tmp_22_fu_924_p2 = ((ap_phi_mux_state_s_phi_fu_676_p30 == 5'd7) ? 1'b1 : 1'b0);

assign tmp_23_fu_930_p2 = ((ap_phi_mux_state_s_phi_fu_676_p30 == 5'd9) ? 1'b1 : 1'b0);

assign tmp_24_fu_792_p4 = {{poke_V_tag_dout[31:8]}};

assign tmp_27_fu_936_p2 = ((ap_phi_mux_state_s_phi_fu_676_p30 == 5'd10) ? 1'b1 : 1'b0);

assign tmp_28_fu_942_p2 = ((ap_phi_mux_state_s_phi_fu_676_p30 == 5'd11) ? 1'b1 : 1'b0);

assign tmp_29_fu_948_p2 = ((ap_phi_mux_state_s_phi_fu_676_p30 == 5'd12) ? 1'b1 : 1'b0);

assign tmp_2_fu_772_p1 = poke_V_data_dout[2:0];

assign tmp_30_fu_954_p2 = ((ap_phi_mux_state_s_phi_fu_676_p30 == 5'd13) ? 1'b1 : 1'b0);

assign tmp_31_fu_960_p2 = ((ap_phi_mux_state_s_phi_fu_676_p30 == 5'd14) ? 1'b1 : 1'b0);

assign tmp_32_fu_966_p2 = ((ap_phi_mux_state_s_phi_fu_676_p30 == 5'd15) ? 1'b1 : 1'b0);

assign tmp_33_fu_972_p2 = ((ap_phi_mux_state_s_phi_fu_676_p30 == 5'd16) ? 1'b1 : 1'b0);

assign tmp_34_fu_1025_p1 = tmp_fu_494[31:0];

assign tmp_35_fu_1029_p2 = (tmp_34_fu_1025_p1 | ap_reg_pp0_iter1_tmp_data_reg_1165);

assign tmp_36_fu_1034_p4 = {{tmp_fu_494[63:32]}};

assign tmp_38_fu_1002_p2 = ((ap_reg_pp0_iter1_tmp_data_reg_1165 != 32'd0) ? 1'b1 : 1'b0);

assign tmp_3_fu_808_p2 = ((poke_V_tag_dout == 32'd16) ? 1'b1 : 1'b0);

assign tmp_4_fu_814_p2 = ((poke_V_tag_dout == 32'd24) ? 1'b1 : 1'b0);

assign tmp_5_fu_820_p2 = ((poke_V_tag_dout == 32'd28) ? 1'b1 : 1'b0);

assign tmp_6_fu_826_p2 = ((poke_V_tag_dout == 32'd32) ? 1'b1 : 1'b0);

assign tmp_7_fu_832_p2 = ((poke_V_tag_dout == 32'd40) ? 1'b1 : 1'b0);

assign tmp_8_fu_838_p2 = ((poke_V_tag_dout == 32'd44) ? 1'b1 : 1'b0);

assign tmp_9_fu_844_p2 = ((poke_V_tag_dout == 32'd48) ? 1'b1 : 1'b0);

assign tmp_s_fu_850_p2 = ((poke_V_tag_dout == 32'd52) ? 1'b1 : 1'b0);

assign tmp_sector_num_1_fu_1106_p1 = req_sector_num_fu_1100_p2;

assign tmp_sector_num_3_fu_1072_p1 = req_sector_num_1_fu_1066_p2;

assign tmp_tag_1_fu_1121_p1 = $signed(req_tag_fu_1115_p2);

assign tmp_tag_3_fu_1087_p1 = $signed(req_tag_1_fu_1081_p2);

assign write_mode_app_buf_addrs_V_din = ap_reg_pp0_iter1_tmp_data_reg_1165;

assign write_total_len_2_fu_1044_p3 = {{tmp_36_fu_1034_p4}, {tmp_35_fu_1029_p2}};

assign write_total_len_fu_1010_p3 = {{ap_reg_pp0_iter1_tmp_data_reg_1165}, {32'd0}};

endmodule //poke_handler
