#ifndef CONST_H
#define CONST_H

#define FIRST_MINOR (0)
#define MINOR_CNT (16)

#define HEAD_CNT (128)
#define SECTOR_CNT (128)
#define CYLINDER_CNT (8192)
#define PHYSICAL_SECTOR_SIZE (4096)
#define LOGICAL_SECTOR_SIZE (512)
#define LOGICAL_SECTOR_SIZE_LOG2 (9)

#define DEVICE_SIZE (HEAD_CNT * SECTOR_CNT * CYLINDER_CNT)
#define DEVICE_NAME ("nvme_fpga")
#define DEVICE_PCIE_WIDTH (64)
#define DEVICE_REQ_QUEUE_DEPTH (64) // must be the power of 2

#define MASK_MIN (7)
#define BITMAP_CHUNK_NUM (4)
#define BITMAP_CHUNK_SIZE (DEVICE_REQ_QUEUE_DEPTH / BITMAP_CHUNK_NUM)

#define PHY_MEM_BASE_ADDR (0x82000000)
#define PHY_MEM_SIZE (32 * (1 << 20)) // 32MB

#define READ_CMD_TAG_OFFSET (64)
#define WRITE_CMD_TAG_OFFSET (128)
#define KBUF_ADDR_TAG (4)
#define HOST_DELAY_CYCLE_TAG (5)
#define HOST_THROTTLE_PARAM_TAG (6)
#define DEVICE_DELAY_CYCLE_TAG (7)
#define DEVICE_THROTTLE_PARAM_TAG (8)

#define HOST_READ_THROTTLE_PARAM (0)
#define HOST_WRITE_THROTTLE_PARAM (0)
#define DEVICE_DELAY_CYCLE_CNT (250)
#define DEVICE_READ_THROTTLE_PARAM (0)
#define DEVICE_WRITE_THROTTLE_PARAM (0)

#define WRITE_TYPE (0)
#define READ_TYPE (1)

#endif
